### ISSUE TITLE
Optional 'text': Fetch text by uid

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/semantic-search#10]
Disclaimer: 'nice to have' / future

Background: Currently, API requires query/documents to include `uid`, `text`. In particular, the client must supply text information, and this has already required modifications to the semantic-search server to accept large payloads and imposes overhead.  

Proposal: Accept `text` as optional; default is to retrieve text information based upon `uid`. Should return  identical information (list of `uid`, `score`)

Details: If supplied, use `text` for downstream analysis; This is necessary in case there is no pubmed record. Currently Factoid just makes up a dummy uid. Can accept opt telling system what namespace uid is (PMCID, PMID etc)

**Comment by maxkfranz** [comment]
If we use this approach to remove step (1)(c) in https://github.com/PathwayCommons/factoid/issues/775, then the response from Semantic Search should include the full Pubmed metadata for each sorted article.

**Comment by jvwong** [comment]
Note to self: Append title + abstract
