### ISSUE TITLE
README instructions for linting and testing

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/semantic-search#109]
Make clear how to test and lint (for the uninitiated) - so I can make sure I didn't break anything !

**Comment by JohnGiorgi** [comment]
Yes this is a good idea. I will add a `CONTRIBUTING.md` file to the repo, I think this is the canonical place to put this information.

For now, the commands are:

- `black .` to format the code base
- `flake8 .` to lint the code
- `pytest` to run the tests. You can pass a file name to run only the tests in that file.
