### ISSUE TITLE
Using a domain-specific model.

### ISSUE THREAD

**Issue by JohnGiorgi** [PathwayCommons/semantic-search#29]
Hey @jvwong, I just trained a new model on 2 million scientific papers from the [S2ORC](https://github.com/allenai/s2orc/) corpus. I want to see if it performs better than our current model for semantic search.

Did you have some kind of dataset or test for determining performance (even qualitatively?) I tried using [MedSentEval](https://github.com/nstawfik/MedSentEval) and got _somewhere_, but I ran into a lot of issues so I gave up.

The models I wanted to compare can be loaded in `semantic-search` as follows:

```bash
# The current model (small)
CUDA_DEVICE=0 PRETRAINED_MODEL_NAME_OR_PATH="johngiorgi/declutr-base" MAX_LENGTH=384 uvicorn semantic_search.main:app

# The current model (base)
CUDA_DEVICE=0 PRETRAINED_MODEL_NAME_OR_PATH="johngiorgi/declutr-small" MAX_LENGTH=384 uvicorn semantic_search.main:app

# AllenAI's SciBERT
CUDA_DEVICE=0 PRETRAINED_MODEL_NAME_OR_PATH="allenai/scibert_scivocab_uncased" MAX_LENGTH=384 uvicorn semantic_search.main:app

# AllenAI's SciBERT trained on 2 million extra papers with our DeCLUTR process
CUDA_DEVICE=0 PRETRAINED_MODEL_NAME_OR_PATH="johngiorgi/declutr-sci-base" MAX_LENGTH=384 uvicorn semantic_search.main:app
```

[SciBERT](https://github.com/allenai/scibert) is the model that [the paper](https://mc.ai/aspect-based-document-similarity-for-research-papers%E2%80%8A-%E2%80%8Aread-a-paper/) @gbader mentioned found to work well for scientific semantic search. In my testing, it gives dissimilar abstracts very high similarity scores (e.g. >80%). After fine-tuning it with our DeCLUTR process, the results look a lot better.

If `"johngiorgi/declutr-sci-base"` does perform the best, I will set it as the default model in `semantic-search`.

**Comment by jvwong** [comment]
I had this way back when: https://github.com/jvwong/filterGene2Pubmed/blob/09de9db7f64fb76754ff386efb6e00ac17cf9c04/harness.txt

**Comment by jvwong** [comment]
@JohnGiorgi I dumped the results here: https://github.com/jvwong/filterGene2Pubmed/tree/master/iss29

I ran each model and named the tsv results according to the  `PRETRAINED_MODEL_NAME_OR_PATH` path

There's probably a more rigorous criteria of evaluating these but looks to me like  `scibert_scivocab_uncased` worked best if you look at the top 43 or so results with respect to position and number of errors.

**Comment by JohnGiorgi** [comment]
Gotcha, thanks. I will take a look at this.

I ended up evaluating on the BIOSESS dataset, which should be a good proxy for the related paper feature of BioFactoid and `"johngiorgi/declutr-sci-base"` came out on top with a healthy margin.

I will look for additional evaluation datasets to test the relative performance of these models.
