### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/semantic-search#3]
- Create Dockerfile 
- Create [PC Dockerhub](https://hub.docker.com/?ref=login) image to autobuild from this remote

**Comment by metincansiper** [comment]
I added the docker file in a branch called ``docker`` and created a PR (#4) for from that. I created an automated build out of the ``docker`` branch for now. Once it is merged I can edit it so that the ``master`` branch will be used instead.
