### ISSUE TITLE
NCBI PubMed EUTILS: article edge cases

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/semantic-search#46]
There are cases where 1. The title tag is empty (e.g. PMID: 33279447) and 2. AbstractText tags can be empty (e.g. 33278872)

Since we will still use the dynamic fetch from NCBI EUTILS for the foreseeable future, we should accommodate these edge cases: see solutions in https://github.com/PathwayCommons/pubmed-dl/pull/4/commits/aeeb125579f3847f42c8d65c1405435996335e56 allows 

Thanks @Anwesh1 for the leg work.

**Comment by jvwong** [comment]
- copy paste in new module
- modularize and share between both projects if possible
-

**Comment by JohnGiorgi** [comment]
@jvwong @Anwesh1 Can this be closed?

**Comment by jvwong** [comment]
yes
