### ISSUE TITLE
Allow duplicate libraries to be open (os.environ)

### ISSUE THREAD

**Issue by Anwesh1** [PathwayCommons/semantic-search#53]
Find a better way of allowing the presence of duplicate libraries instead of this hotfix.
https://github.com/PathwayCommons/semantic-search/blob/b9f93d776ecb495fc68c9e7562f0b62701d88f00/semantic_search/main.py#L19-L20

Error without the hotfix is: 
```
OMP: Error #15: Initializing libomp.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
```

**Comment by Anwesh1** [comment]
Hey, @JohnGiorgi is this issue fixed? When I remove that line and run on Insomnia, it works fine without an error.

**Comment by JohnGiorgi** [comment]
Nope, I still get the error without that line (just checked). I am on MacOS, so perhaps it is MacOS specific.

**Comment by Anwesh1** [comment]
Yeah, that might be a reason. I'm running on Linux and it works the same if the line is present or absent.

**Comment by JohnGiorgi** [comment]
I see. A slight improvement to our current solution, then, could be to try and determine if the user is on macOS, and only if they are, run this line.

**Comment by Anwesh1** [comment]
Yeah, that makes sense. This can't be run on Windows platforms anyway because FAISS doesn't have any support for Windows. So we just need to worry bout Linux and Mac
