### ISSUE TITLE
If PMID present in index, then we don't need to fetch the text

### ISSUE THREAD

**Issue by Anwesh1** [PathwayCommons/semantic-search#55]
If PMID and text are already in the index, the program is still fetching text. 

Need to change it so that if PMID is present in the index then we just get the values from the index instead of having to fetch it

**Comment by jvwong** [comment]
Re format for a PubMed uid (only postitive integers?): 

So here's the github issue I had regarding uids: https://github.com/PathwayCommons/factoid/issues/595

**Comment by Anwesh1** [comment]
Hey @JohnGiorgi, I'm doing the fix that we talked about on our call. Where we essentially loop through all the id's and see the ones that don't have texts.
-> `fetch_text = [id_ for id_, text in zip(ids, texts) if text is None]`

However, by this point, we already have all the texts so the above line essentially returns an empty list. If I'm not wrong we get all our `uid` and `texts` in this line, when `Query` is called:
https://github.com/PathwayCommons/semantic-search/blob/ef1f28f57b7529972a8e33d0a909f65a6fc37648/semantic_search/main.py#L87

I know we talked about removing the majority of the chunk of code from the validator and putting it in a separate function.
I wanted to hop on a quick call with you if you are free sometime, just so I can talk with you about some implementation questions because I'm a little stuck on how the structure would possibly look like and have a few smaller questions on how the process would work. Let me know.

**Comment by JohnGiorgi** [comment]
Hey @Anwesh1,

> However, by this point, we already have all the texts so the above line essentially returns an empty list. If I'm not wrong we get all our uid and texts in this line, when Query is called:

Technically this happens in the validator, here: https://github.com/PathwayCommons/semantic-search/blob/0623d2b04a08c39fc47a6a585d5d085319247364/semantic_search/schemas.py#L33-L44. You will need to remove this entire validator. Does that help get you started?

**Comment by Anwesh1** [comment]
Sure @JohnGiorgi. I was thinking of moving the code in the validator to the beginning of the method in `main.py`. I will play around with that and keep you updated. Thanks

**Comment by Anwesh1** [comment]
Hey @JohnGiorgi, a few questions:

1. We discussed removing the validator inside the `Query` class. However, the class needs to return a list apparently, otherwise, it throws errors. I'm confused here because all other classes just require their variable, but for this class it requires a list to be returned. Not sure how I bypass that.
2. I was planning on moving the function to the `util.py` file but I don't know what I use for its argument list. right now it is taking in three arguments -> `def normalize_document(cls, v, field):`. So I'm not sure how these arguments correlate when removed from the validator.
3. I understand the structure of how the whole process should work but I'm having difficulty in implementing the code without errors.

Please let me know if you could assist, thank you.

**Comment by JohnGiorgi** [comment]
Hey @Anwesh1,

1. Whenever you are asking a question about a specific error, it's good practice to provide a simple example that triggers the error. Copy, paste and format that example here, along with the stack trace that it generates. Can you do that for 1), and then I can maybe be of more help?
2. `cls`, `v` and `field` can all be dropped, these were specific to the validator. Just think in terms of what you want to accomplish. Given a list of `pmids` (`List[str]`) you want to return the text (title + abstract) for each of those PMIDs (`List[str]`). Your function header therefore looks something like:

```python
def normalize_documents(pmids: List[str]) -> List[str]
```

**Comment by Anwesh1** [comment]
As for the error I talked about before, I just commented out the validator to see how it would work:

![image](https://user-images.githubusercontent.com/57552053/113049806-146e3c00-9172-11eb-8cde-fa77559c1bd8.png)

I got a POST request error with the message that the 'value is not a valid dict' so that was confusing to me:
 
![image](https://user-images.githubusercontent.com/57552053/113049920-3962af00-9172-11eb-86bc-9012a39605ac.png)

**Comment by JohnGiorgi** [comment]
> As for the error I talked about before, I just commented out the validator to see how it would work:
> 
> ![image](https://user-images.githubusercontent.com/57552053/113049806-146e3c00-9172-11eb-8cde-fa77559c1bd8.png)
> 
> I got a POST request error with the message that the 'value is not a valid dict' so that was confusing to me:
> 
> ![image](https://user-images.githubusercontent.com/57552053/113049920-3962af00-9172-11eb-86bc-9012a39605ac.png)

I would need to see the body of your POST request.

**Comment by Anwesh1** [comment]
Sorry, I will copy/paste.
This is the `Query` class that I changed because I wanted to see how it affects the process.

```python
class Query(BaseModel):
    query: Document
    documents: List[Document] = []
    top_k: int = Field(10, gt=0, description="top_k must be greater than 0")
"""
    @validator("query", "documents", pre=True)
    def normalize_document(cls, v, field):
        if field.name == "query":
            v = [v]
        normalized_docs = []
        for doc in v:
            if isinstance(doc, UID):
                # uids_to_docs expects a list of strings and yields a list of dictionaries. We
                # convert the generator to a list, and then index its first element, and then
                # unpack the dictionary and pass its contents as keyword arguments to Document.
                normalized_docs.append(Document(**list(uids_to_docs([doc]))[0][0]))
            else:
                normalized_docs.append(doc)
        return normalized_docs[0] if field.name == "query" else normalized_docs
"""
```

This is the POST request made 
```json
{
    "query": "9887103",
    "documents": ["9887103", "30049242", "22936248"],
    "top_k": 2
}
```

This was the 422 (unprocessable entity) error
```json
{
  "detail": [
    {
      "loc": [
        "body",
        "query"
      ],
      "msg": "value is not a valid dict",
      "type": "type_error.dict"
    },
    {
      "loc": [
        "body",
        "documents",
        0
      ],
      "msg": "value is not a valid dict",
      "type": "type_error.dict"
    },
    {
      "loc": [
        "body",
        "documents",
        1
      ],
      "msg": "value is not a valid dict",
      "type": "type_error.dict"
    },
    {
      "loc": [
        "body",
        "documents",
        2
      ],
      "msg": "value is not a valid dict",
      "type": "type_error.dict"
    }
  ]
}
```

I'm not sure how much this really affects what we're doing but I just want to understand how the `Query` class exactly works and how we can sort of use that.

**Comment by JohnGiorgi** [comment]
> Sorry, I will copy/paste.
> This is the `Query` class that I changed because I wanted to see how it affects the process.
> 
> ```python
> class Query(BaseModel):
>     query: Document
>     documents: List[Document] = []
>     top_k: int = Field(10, gt=0, description="top_k must be greater than 0")
> """
>     @validator("query", "documents", pre=True)
>     def normalize_document(cls, v, field):
>         if field.name == "query":
>             v = [v]
>         normalized_docs = []
>         for doc in v:
>             if isinstance(doc, UID):
>                 # uids_to_docs expects a list of strings and yields a list of dictionaries. We
>                 # convert the generator to a list, and then index its first element, and then
>                 # unpack the dictionary and pass its contents as keyword arguments to Document.
>                 normalized_docs.append(Document(**list(uids_to_docs([doc]))[0][0]))
>             else:
>                 normalized_docs.append(doc)
>         return normalized_docs[0] if field.name == "query" else normalized_docs
> """
> ```
> 
> This is the POST request made
> 
> ```json
> {
>     "query": "9887103",
>     "documents": ["9887103", "30049242", "22936248"],
>     "top_k": 2
> }
> ```
> 
> This was the 422 (unprocessable entity) error
> 
> ```json
> {
>   "detail": [
>     {
>       "loc": [
>         "body",
>         "query"
>       ],
>       "msg": "value is not a valid dict",
>       "type": "type_error.dict"
>     },
>     {
>       "loc": [
>         "body",
>         "documents",
>         0
>       ],
>       "msg": "value is not a valid dict",
>       "type": "type_error.dict"
>     },
>     {
>       "loc": [
>         "body",
>         "documents",
>         1
>       ],
>       "msg": "value is not a valid dict",
>       "type": "type_error.dict"
>     },
>     {
>       "loc": [
>         "body",
>         "documents",
>         2
>       ],
>       "msg": "value is not a valid dict",
>       "type": "type_error.dict"
>     }
>   ]
> }
> ```
> 
> I'm not sure how much this really affects what we're doing but I just want to understand how the `Query` class exactly works and how we can sort of use that.

`Query` is just a pydantic model. I would encourage you to read through the relevant [FastAPI docs](https://fastapi.tiangolo.com/tutorial/body/) and [Pydantic Docs](https://pydantic-docs.helpmanual.io/usage/models/).

**Comment by Anwesh1** [comment]
When I set up a POST request (after commenting out the validator) with just `uids` I keep running into the same error, even though I set the text to be Optional. Is there a way to fix that possibly? Went I make a request with the `uids` and `text` then it works completely fine. However, just with `uids` is the same error I mentioned above.

**Comment by JohnGiorgi** [comment]
> When I set up a POST request (after commenting out the validator) with just `uids` I keep running into the same error, even though I set the text to be Optional. Is there a way to fix that possibly? Went I make a request with the `uids` and `text` then it works completely fine. However, just with `uids` is the same error I mentioned above.

The POST request body style that just contains a list of UIDs is no longer supported when you drop the validator, e.g.

```json
{
    "query": "9887103",
    "documents": ["9887103", "30049242", "22936248"],
    "top_k": 2
}
```

You will need to replace it with the other style of request e.g. 

```json
{
    "query": {
        "uid":"9887103",
     },
    "documents":[
        {
            "uid": "9887103",
        },
        {
            "uid": "30049242",
        },
        {
            "uid": "22936248",
         }
    ],
    "top_k":2
}

This is also inline with our discussions in #65.

**Comment by JohnGiorgi** [comment]
> Is there a quick way to just get the value instead of the address for a generator?

Use something like what we have in the validator:

https://github.com/PathwayCommons/semantic-search/blob/ef1f28f57b7529972a8e33d0a909f65a6fc37648/semantic_search/schemas.py#L35

> Also does my implementation align with what we want to do.

Does this prevent the same text from being retrieved if its UID already exists in the index? If so, yes.

**Comment by Anwesh1** [comment]
I had done that before but the return looked like this, where `text` was a `Document` type, when it's just supposed to be a `str` that's why I changed it:
 ```
Query(query=Document(uid='9887103', text=[Document(uid='9887103', text='The Drosophila activin receptor baboon signals through dSmad2 and controls cell proliferation but not patterning during larval development. The TGF-beta superfamily of growth and differentiation factors, including TGF-beta, Activins and bone morphogenetic proteins (BMPs) play critical roles in regulating the development of many organisms. These factors signal through a heteromeric complex of type I and II serine/threonine kinase receptors that phosphorylate members of the Smad family of transcription factors, thereby promoting their nuclear localization. Although components of TGF-beta/Activin signaling pathways are well defined in vertebrates, no such pathway has been clearly defined in invertebrates. In this study we describe the role of Baboon (Babo), a type I Activin receptor previously called Atr-I, in Drosophila development and characterize aspects of the Babo intracellular signal-transduction pathway. Genetic analysis of babo loss-of-function mutants and ectopic activation studies indicate that Babo signaling plays a role in regulating cell proliferation. In mammalian cells, activated Babo specifically stimulates Smad2-dependent pathways to induce TGF-beta/Activin-responsive promoters but not BMP-responsive elements. Furthermore, we identify a new Drosophila Smad, termed dSmad2, that is most closely related to vertebrate Smads 2 and 3. Activated Babo associates with dSmad2 but not Mad, phosphorylates the carboxy-terminal SSXS motif and induces heteromeric complex formation with Medea, the Drosophila Smad4 homolog. Our results define a novel Drosophila Activin/TGF-beta pathway that is analogous to its vertebrate counterpart and show that this pathway functions to promote cellular growth with minimal effects on patterning.')]), documents=[Document(uid='9887103', text=None), Document(uid='30049242', text=None), Document(uid='22936248', text=None)], top_k=2)
```

There is also another error when I do it like the validator way:
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "./semantic_search/main.py", line 125, in query
    embeddings = encode(texts).cpu().numpy()
  File "./semantic_search/main.py", line 55, in encode
    Tuple[Tuple[int], List[str]], zip(*sorted(enumerate(text), key=itemgetter(1)))
TypeError: '<' not supported between instances of 'Document' and 'Document'
```

**Comment by JohnGiorgi** [comment]
> I had done that before but the return looked like this, where `text` was a `Document` type, when it's just supposed to be a `str` that's why I changed it:
> 
>  ```
> 
> Query(query=Document(uid='9887103', text=[Document(uid='9887103', text='The Drosophila activin receptor baboon signals through dSmad2 and controls cell proliferation but not patterning during larval development. The TGF-beta superfamily of growth and differentiation factors, including TGF-beta, Activins and bone morphogenetic proteins (BMPs) play critical roles in regulating the development of many organisms. These factors signal through a heteromeric complex of type I and II serine/threonine kinase receptors that phosphorylate members of the Smad family of transcription factors, thereby promoting their nuclear localization. Although components of TGF-beta/Activin signaling pathways are well defined in vertebrates, no such pathway has been clearly defined in invertebrates. In this study we describe the role of Baboon (Babo), a type I Activin receptor previously called Atr-I, in Drosophila development and characterize aspects of the Babo intracellular signal-transduction pathway. Genetic analysis of babo loss-of-function mutants and ectopic activation studies indicate that Babo signaling plays a role in regulating cell proliferation. In mammalian cells, activated Babo specifically stimulates Smad2-dependent pathways to induce TGF-beta/Activin-responsive promoters but not BMP-responsive elements. Furthermore, we identify a new Drosophila Smad, termed dSmad2, that is most closely related to vertebrate Smads 2 and 3. Activated Babo associates with dSmad2 but not Mad, phosphorylates the carboxy-terminal SSXS motif and induces heteromeric complex formation with Medea, the Drosophila Smad4 homolog. Our results define a novel Drosophila Activin/TGF-beta pathway that is analogous to its vertebrate counterpart and show that this pathway functions to promote cellular growth with minimal effects on patterning.')]), documents=[Document(uid='9887103', text=None), Document(uid='30049242', text=None), Document(uid='22936248', text=None)], top_k=2)
> 
> ```
> 
> 
> 
> There is also another error when I do it like the validator way:
> 
> ```bash
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
> 
>     result = await app(self.scope, self.receive, self.send)
> 
>   File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
> 
>     return await self.app(scope, receive, send)
> 
>   File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 199, in __call__
> 
>     await super().__call__(scope, receive, send)
> 
>   File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 111, in __call__
> 
>     await self.middleware_stack(scope, receive, send)
> 
>   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 181, in __call__
> 
>     raise exc from None
> 
>   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 159, in __call__
> 
>     await self.app(scope, receive, _send)
> 
>   File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in __call__
> 
>     raise exc from None
> 
>   File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in __call__
> 
>     await self.app(scope, receive, sender)
> 
>   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 566, in __call__
> 
>     await route.handle(scope, receive, send)
> 
>   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 227, in handle
> 
>     await self.app(scope, receive, send)
> 
>   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 41, in app
> 
>     response = await func(request)
> 
>   File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 201, in app
> 
>     raw_response = await run_endpoint_function(
> 
>   File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 148, in run_endpoint_function
> 
>     return await dependant.call(**values)
> 
>   File "./semantic_search/main.py", line 125, in query
> 
>     embeddings = encode(texts).cpu().numpy()
> 
>   File "./semantic_search/main.py", line 55, in encode
> 
>     Tuple[Tuple[int], List[str]], zip(*sorted(enumerate(text), key=itemgetter(1)))
> 
> TypeError: '<' not supported between instances of 'Document' and 'Document'
> 
> ```

You need to access the `text` attribute which is a string. So `document.text`.

**Comment by Anwesh1** [comment]
Hey, @JohnGiorgi I think we can close this issue now?
