### ISSUE TITLE
Flag to use index

### ISSUE THREAD

**Issue by JohnGiorgi** [PathwayCommons/semantic-search#61]
Each query should allow for a flag (say `use_index`) that allows the user to not use/not use an index.

**Comment by jvwong** [comment]
@JohnGiorgi Do you think it's feasible/trivial to handle the following scenario: A request is made, having any of the existing required information (`uid`, `text`), however the response is restricted to the `documents`. In particular, the index can be updated and queried as usual.

In my mind, this just means picking off the uids in the `document` request and sending those back, but I'm not sure if all docs are ranked?

Refs https://github.com/PathwayCommons/semantic-search/issues/81#issuecomment-819771122

**Comment by JohnGiorgi** [comment]
I think I understand. Is this the exact same idea as https://github.com/PathwayCommons/semantic-search/issues/81#issuecomment-819771122, where there's some parameter passed in with a request, e.g. `use_index`, and if it's `False`, we only consider the `uids` in `documents`?

**Comment by jvwong** [comment]
> I think I understand. Is this the exact same idea as [#81 (comment)](https://github.com/PathwayCommons/semantic-search/issues/81#issuecomment-819771122), where there's some parameter passed in with a request, e.g. `use_index`, and if it's `False`, we only consider the `uids` in `documents`?
> 
> Alternatively, we could assume that if `documents` is not empty, we should only return `uids` from it and not the index.
> 

Yeah, the key point is that the set of uids provided get returned to the client. It could still use the index. 

> I think I could implement either pretty quickly.

Sure that would be helpful, let me know if I can help.

**Comment by jvwong** [comment]
I'll take a stab at this - To test I guess we would need some mock/spy ?

**Comment by JohnGiorgi** [comment]
Right so I think you would basically add some argument to [`Search`](https://github.com/PathwayCommons/semantic-search/blob/ba9940095cf35b01cee30f1bd807652cf38545b7/semantic_search/schemas.py#L19) that is considered by the [`search`](https://github.com/PathwayCommons/semantic-search/blob/ba9940095cf35b01cee30f1bd807652cf38545b7/semantic_search/main.py#L134) function of `main.py`.

Then, you could copy and modify [`dummy_request_with_test()`](https://github.com/PathwayCommons/semantic-search/blob/ba9940095cf35b01cee30f1bd807652cf38545b7/tests/conftest.py#L21) in `conftest.py`, and add a test for it in [`test_main.py`](https://github.com/PathwayCommons/semantic-search/blob/main/tests/test_main.py) to ensure this new argument is doing what it is supposed to.
