### ISSUE TITLE
Deploy streamlit demo

### ISSUE THREAD

**Issue by JohnGiorgi** [PathwayCommons/semantic-search#77]
Deploy the streamlit app following the instructions [here](https://docs.streamlit.io/en/stable/deploy_streamlit_app.html). Currently waiting to be granted access to Streamlit for Teams.

**Comment by maxkfranz** [comment]
Could the app be deployed normally?  My understanding is that the teams deployment is primarily for when you want to publish private apps.

I already have access to sharing public apps on Streamlit.
