### ISSUE TITLE
Sanity check performance (classification)

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/semantic-search#88]
In #29 we developed a test set with a query and articles labelled as positive (related) vs negative (not related).

Proposal: Reuse this set to run a sanity check on the results of the updated codebase

Will post performance

See https://github.com/PathwayCommons/semantic-search/issues/29#issuecomment-724270778

**Comment by JohnGiorgi** [comment]
Cool, let me know if anything break while you are testing

**Comment by jvwong** [comment]
|uid     |score              |indicator|
|--------|-------------------|---------|
|10320478|0.8779383301734924 |1        |
|20346940|0.8694853186607361 |1        |
|17119022|0.8434889316558838 |1        |
|23293296|0.8423692584037781 |1        |
|12581521|0.8408995270729065 |1        |
|22563507|0.8246047496795654 |1        |
|24706779|0.8218140602111816 |1        |
|17119021|0.8172059059143066 |1        |
|25255438|0.8142316341400146 |1        |
|16437159|0.8093700408935547 |1        |
|19766717|0.8079355359077454 |1        |
|18820452|0.8073562383651733 |1        |
|25633355|0.8067716360092163 |1        |
|9813169 |0.8061860203742981 |1        |
|18588885|0.8030333518981934 |1        |
|19004854|0.802139937877655  |1        |
|28108836|0.8016126155853271 |1        |
|10357889|0.7987509965896606 |1        |
|16098524|0.7983336448669434 |1        |
|16951053|0.7965449094772339 |1        |
|17651718|0.7965002059936523 |1        |
|30049242|0.7961974143981934 |1        |
|15473904|0.7939726114273071 |1        |
|28130362|0.7902795076370239 |0        |
|28123053|0.7851442694664001 |1        |
|22874913|0.7844593524932861 |1        |
|23664613|0.781703531742096  |1        |
|23416177|0.7813857197761536 |1        |
|10831835|0.777236819267273  |1        |
|18077144|0.7755217552185059 |1        |
|18171686|0.7694700360298157 |1        |
|25284780|0.7606640458106995 |1        |
|24462039|0.7529500722885132 |1        |
|10712925|0.7496800422668457 |0        |
|29615416|0.7484028339385986 |0        |
|18054857|0.7427711486816406 |1        |
|28853393|0.7394638061523438 |1        |
|28748922|0.7364281415939331 |1        |
|14605208|0.73134446144104   |0        |
|20220848|0.7232170104980469 |0        |
|26667894|0.720421552658081  |0        |
|28178568|0.7108768224716187 |1        |
|23485686|0.7078301906585693 |1        |
|12537574|0.7056390047073364 |0        |
|24680699|0.7035620808601379 |1        |
|12537572|0.6984351873397827 |0        |
|24793180|0.6946649551391602 |0        |
|21613324|0.6944917440414429 |1        |
|10731132|0.6891192197799683 |0        |
|23345225|0.6797980070114136 |1        |
|28739899|0.6748075485229492 |1        |
|22936248|0.6746125221252441 |0        |
|15018941|0.6742993593215942 |0        |
|17434471|0.6704286336898804 |1        |
|20800474|0.6663018465042114 |0        |
|23072462|0.6632452011108398 |0        |
|12537573|0.6579042077064514 |0        |
|24244197|0.644208550453186  |1        |
|17569867|0.6413986682891846 |0        |
|28421183|0.6309901475906372 |0        |
|17569856|0.6303260326385498 |0        |
|24912777|0.6077055931091309 |0        |
|23071443|0.6076573133468628 |0        |
|25312911|0.603297233581543  |0        |
|16110336|0.5817238092422485 |0        |
|12537568|0.5718622207641602 |0        |
|26109357|0.5374062061309814 |0        |
|26109356|0.5013960599899292 |0        |
|15046717|0.4300670921802521 |0        |
|10733523|0.30555495619773865|0        |
|9887103 |                   |1        |

**Comment by jvwong** [comment]
Notes on how fast this works: 
- Query 1: 71 document uids; ~1m 30s
- Query 2: 71 cached uids + 1 unseen;  ~2s
